using ODLMWebAPI.Models;
using System;
using System.Collections.Generic;
using ODLMWebAPI.StaticStuff;
using System.Data.SqlClient;
using System.Data;

namespace simpliMASTERSAPI.BL.Interfaces
{
    public interface ITblFinLedgerBL
    {
        List<TblFinLedgerTO> SelectChildLedgerList(long parentFinLedgerId);
        TblFinLedgerTO SelectLedgerTO(long finLedgerId);
        List<DropDownTO> SelectFinActTypeDropDownList();
        List<DropDownTO> SelectFinProjectsDropDownList();
        ResultMessage SaveNewLedgerOrGroup(TblFinLedgerTO tblFinLedgerTO);
        ResultMessage UpdateFinLedger(TblFinLedgerTO tblFinLedgerTO);
        ResultMessage MigrateDefaultChartOfActFromSAP();

        List<TblFinLedgerTO> SelectLedgerForSearchList(string LedgerName, string LedgerCode, Int32 Type);

        List<TblFinLedgerTO> SelectLedgerListByParentId(long parentFinLedgerId);

        ResultMessage ImportExcelCOAToSystem(DataTable dataTable);
        ResultMessage GetAutoGeneratedLedgerCode(Int32 ledgerTypeId, long parentFinLedgerId);
        string GetAutoGeneratedSAPLedgerCode();
    }
}
