using ODLMWebAPI.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace simpliMASTERSAPI.DAL.Interfaces
{
    public interface ITblFinLedgerDAO
    {
        String SqlSelectQuery();

        List<TblFinLedgerTO> SelectChildLedgerList(long parentFinLedgerId);
        List<TblFinLedgerTO> SelectChildLedgerListFromSAP(String parentLedgerCode);
        TblFinLedgerTO SelectLedgerTO(long finLedgerId);
        List<DropDownTO> SelectFinActTypeDropDownList();
        List<DropDownTO> SelectFinProjectsDropDownList();
        int InsertTblFinLedger(TblFinLedgerTO tblFinLedgerTO);
        int InsertTblFinLedger(TblFinLedgerTO tblFinLedgerTO, SqlConnection conn, SqlTransaction tran);
        int UpdateTblFinLedger(TblFinLedgerTO tblFinLedgerTO);
        int UpdateTblFinLedger(TblFinLedgerTO tblFinLedgerTO, SqlConnection conn, SqlTransaction tran);

        Boolean isDuplicateLedgerCode(String LedgerCode, String LedgerName, Int32 type, Int64 idFinLedger = 0);

        List<TblFinLedgerTO> SelectLedgerListForSearch(string LedgerName, string LedgerCode, Int32 Type);

        TblFinLedgerTO SelectLedgerListByParentId(long parentFinLedgerId);
        int GetAutoGeneratedSAPLedgerCode();
    }
}
